### PR TITLE
fix(commands/apm/grant): use updated CREATE_VERSION_ROLE hash

### LINKED ISSUE #158: Update APMRepo create version role hash
When doing `aragon apm grant 0xab` for giving the `CREATE_VERSION_ROLE` to `0xab`, it will do it for the role hash `0x00...01` which was used in the previous versions of aragonOS.

The current correct role hash is `keccak256('CREATE_VERSION_ROLE')`.

For this not to be a backwards incompatible change (there are instances of APM with this role hash deployed on rinkeby), we should add a flag that allows for setting the permission with the legacy role hash(`--legacy-role`). Or even better, a call can be made to the Repo contract to get the id for the role.

### PR DESCRIPTION
**Pull request by PascalPrecht**
As discussed in #158, `apm grant 0xsomeAddress` uses a create version
role id hash that is no longer be used by Repo contracts. This commit
ensures that the new role id is used by fetching it from the dedicated
repo address.

Also, this might be considered a breaking change as the new default for the role id, is `keccak256('CREATE_VERSION_ROLE')` and no longer `0x....01`

Fixes #158

### CODE REVIEW

File: src/acl/index.js [hunk 1]
```diff
@@ -8,11 +8,18 @@ module.exports = (web3) => {
...
+
   return {
-    grant: async (repoAddr, grantee) => {
+    grant: async (repoAddr, grantee, useLegacyRoleId = false) => {
       const acl = await getACL(repoAddr)
 
-      const roleId = '0x0000000000000000000000000000000000000000000000000000000000000001'
+      const roleId = useLegacyRoleId ?
+        '0x0000000000000000000000000000000000000000000000000000000000000001' :
+        await getRoleId(repoAddr)
```
Comment (PascalPrecht) [inline src/acl/index.js]: @izqui in #158 you've said:

> Or even better, a call can be made to the Repo contract to get the id for the role.

While this sounds more like an either/or scenario, I've now implemented both ideas: getting hash id from the contract and explicitly falling back to the legacy id using `--legacy-role`.

It wasn't entirely clear to me if both were desired or just one of those options. Let me know if you want this to be changed.

File: src/acl/index.js [hunk 2]
```diff
@@ -8,11 +8,18 @@ module.exports = (web3) => {
     return new web3.eth.Contract(require('@aragon/os/build/contracts/ACL').abi, aclAddr)
   }
 
+  const getRoleId = async (repoAddr) => {
+    const repo = new web3.eth.Contract(require('@aragon/os/build/contracts/AragonApp').abi, repoAddr)
```
Comment (izqui) [inline src/acl/index.js]: It should be the `Repo` contract rather than `AragonApp`

File: src/cli.js [hunk 3]
```diff
@@ -92,7 +92,11 @@ cmd.option('apm.ens-registry', {
   description: 'Address of the ENS registry',
   default: require('@aragon/aragen').ens
 })
-cmd.group(['apm.ens-registry', 'eth-rpc'], 'APM:')
+cmd.option('legacy-role', {
```
Comment (izqui) [inline src/cli.js]: As commented above it is better to just remove the option and always check the role hash in the contract. However this option would have been better located in the command options directly, as it doesn't need to be a global CLI setting.

https://github.com/aragon/aragon-cli/blob/a7822caef299ea120768d5526b495635ba304b0a/src/commands/apm_cmds/grant.js#L10-L14

File: src/acl/index.js (hunk 1 above)
Comment (izqui) [reply src/acl/index.js]: If we get the role hash directly from the contract there is no need to have an option for supporting the legacy role hash, as the contract will always return the actual role hash for the repo. Sorry the issue description wasn't clear enough 😅

I think we should drop the legacy flag and always use the role of the contract.

File: src/acl/index.js [hunk 4]
```diff
@@ -8,11 +8,18 @@ module.exports = (web3) => {
...
+    const roleId = await repo.methods.CREATE_VERSION_ROLE().call()
```
Comment (izqui) [inline src/acl/index.js]: Missing a return here

File: src/acl/index.js (hunk 2 above)
Comment (PascalPrecht) [reply src/acl/index.js]: Sure! That's what happens when you don't test this on your local machine :) 

Will fix this.

File: src/acl/index.js (hunk 1 above)
Comment (PascalPrecht) [reply src/acl/index.js]: Makes sense. I'll remove it.

File: src/acl/index.js (hunk 4 above)
Comment (PascalPrecht) [reply src/acl/index.js]: Good catch!

**Comment by izqui** [comment]
The way I have tested it is:

```
aragon init test-app
aragon run
apm grant [granted address]
```

After `aragon run` either keep that running or stop it and do `aragon devchain` so the grant command can connect to the running chain.

**Comment by PascalPrecht** [comment]
Thanks for the review @izqui !

Most of your comments boil down to lack of local testing. I'll dig into how to setup a local environment where I can run the code against.

**Comment by izqui** [comment]
@PascalPrecht ping me in aragon.chat if you need help setting it up!

**Comment by PascalPrecht** [comment]
Thank you!!

File: src/acl/index.js (hunk 2 above)
Comment (PascalPrecht) [reply src/acl/index.js]: I'm definitely missing what the granting permission in the context of this command and the system means and how all the smart contracts are related to each other, however, maybe you can give me a little pointer on why `repoAddr` is used on an `AragonApp` contract here: https://github.com/aragon/aragon-cli/blob/master/src/acl/index.js#L3 (instead of `Repo` contract)

Comment (izqui) [reply src/acl/index.js]: There we just need to use the `kernel()` method which `Repo` inherits from `AragonApp`: https://github.com/aragon/aragonOS/blob/dev/contracts/apm/Repo.sol#L6. That could also be `Repo` instead of `AragonApp` and would still work.

**Comment by izqui** [comment]
Tested on both rinkeby and local network and it is working as expected!
