### PR TITLE
Use wsRpc in dao apps command

### LINKED ISSUE #1577: Error: Invalid JSON RPC response on dao apps --all command
## 🐛 Bug Report

The `dao apps -all` command returns the following error when run on mainnet:

```
Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.17.6</center>\r\n</body>\r\n</html>\r\n"
```

Using the infura endpoint doesn't seem to solve the problem.

### PR DESCRIPTION
**Pull request by macor161**
# 🦅 Pull Request Description

- Fixes #1577 

## Rational

The wsRpc provider wasn't used to fetch permissionless apps.

### CODE REVIEW

File: packages/cli/src/commands/dao_cmds/apps.js [hunk 1]
```diff
@@ -115,7 +116,7 @@ export const handler = async function({
         task: async (ctx, task) => {
           appsWithoutPermissions = (
             await getAllApps(daoAddress, {
-              web3,
+              web3: new Web3(wsProvider || web3.currentProvider),
```
Comment (0xGabi) [inline packages/cli/src/commands/dao_cmds/apps.js]: Why do we need to initialize a new Web3 object? Shouldn't be the same as line 107 🤔

Comment (macor161) [reply packages/cli/src/commands/dao_cmds/apps.js]: Good question. Because the `ensureWeb3()` function that generates the `Web3` object doesn't use `wsProvider`. I think this has been fixed in `develop` but not yet on `master`
