### PR TITLE
Fix gasLimit issue for dao new

### LINKED ISSUE #346: dao new fails due to gasLimit on mainnet and rinkeby
``` 
$ dao --use-frame --environment aragon:mainnet new
 ✔ Fetching kit bare-kit.aragonpm.eth@latest
 ✖ Create new DAO from kit
   → Returned error: {"id":5,"jsonrpc":"2.0","error":"exceeds block gas limit"}
   Checking DAO
 ✖ Returned error: {"id":5,"jsonrpc":"2.0","error":"exceeds block gas limit"} 

```

It should be possible to deploy a bare organization within the gas limit.

### PR DESCRIPTION
**Pull request by 0x6431346e**
Fixes #346 

Stole this from https://github.com/aragon/aragon.js/pull/159. 
I think it should have it's own package in the future.

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -93,6 +89,38 @@ const getContract = (pkg, contract) => {
...
+
+  const upperGasLimit = Math.round(blockGasLimit * LAST_BLOCK_GAS_LIMIT_FACTOR)
+  // if estimatedGas is above upperGasLimit, dont modify it
+  if (estimatedGas > upperGasLimit) return estimatedGas // TODO print a warning?
+
+  const bufferedGasLimit = Math.round(estimatedGas * gasFuzzFactor)
+
+  // if bufferedGasLimit is below blockGasLimit, use bufferedGasLimit
+  if (bufferedGasLimit < upperGasLimit) return bufferedGasLimit
+  // otherwise use blockGasLimit
```
Comment (sohkai) [inline src/util.js]: Small comment mismatch, should be `upperGasLimit` here and l119.

File: src/util.js [hunk 2]
```diff
@@ -93,6 +89,38 @@ const getContract = (pkg, contract) => {
...
+  estimatedGas,
+  gasFuzzFactor = DEFAULT_GAS_FUZZ_FACTOR
+) => {
+  // TODO print these values if --debug is passed
+  const latestBlock = await web3.eth.getBlock('latest')
+  const blockGasLimit = latestBlock.gasLimit
+
+  const upperGasLimit = Math.round(blockGasLimit * LAST_BLOCK_GAS_LIMIT_FACTOR)
+  // if estimatedGas is above upperGasLimit, dont modify it
+  if (estimatedGas > upperGasLimit) return estimatedGas // TODO print a warning?
```
Comment (sohkai) [inline src/util.js]: Not sure how best to instrument this with logging, especially if we pull it out into a generic util, but it would be helpful!

File: src/util.js (hunk 1 above)
Comment (0x6431346e) [reply src/util.js]: I removed the comments, felt too redundant :sweat_smile:

File: src/util.js (hunk 2 above)
Comment (0x6431346e) [reply src/util.js]: Hmm, if we make this a generic utility then we could return all values:
```
{
 recommended: 3,
 estimated: 2,
 buffered: 3,
 lastBlock: 8
}
```

And let the consumer do the logging

File: Specification.md [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+actual gas that will be used, if the contract you are calling depends on the blockhash, blocknumber or any other source of 
+randomness making the gas cost nondeterministic.
+
+E.g.: the [`MiniMeToken`](https://github.com/aragon/aragon-apps/blob/master/shared/minime/contracts/MiniMeToken.sol) contract which snapshots balances at certain block numbers.
+
+Considering the above-mentioned behavior, the CLI should calculate the recommended gas limit as follows:
+- `recommendedGas = estimatedGas`, if `estimatedGas > upperGasLimit` or
+- `recommendedGas = estimatedGas * LAST_BLOCK_GAS_LIMIT_FACTOR` with a maximum value of `upperGasLimit`
+
+Where `upperGasLimit = latestBlock.gasLimit * LAST_BLOCK_GAS_LIMIT_FACTOR`, `LAST_BLOCK_GAS_LIMIT_FACTOR = 1.5` and `LAST_BLOCK_GAS_LIMIT_FACTOR = 0.95`.
```
Comment (0xGabi) [inline Specification.md]:
```suggestion
Where `upperGasLimit = latestBlock.gasLimit * LAST_BLOCK_GAS_LIMIT_FACTOR`, `DEFAULT_GAS_FUZZ_FACTOR = 1.5` and `LAST_BLOCK_GAS_LIMIT_FACTOR = 0.95`.
```

File: Specification.md [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+
+By default `web3.js` uses `web3.eth.Contract.method.myMethod().estimateGas()`, but this value can differ from the 
+actual gas that will be used, if the contract you are calling depends on the blockhash, blocknumber or any other source of 
+randomness making the gas cost nondeterministic.
+
+E.g.: the [`MiniMeToken`](https://github.com/aragon/aragon-apps/blob/master/shared/minime/contracts/MiniMeToken.sol) contract which snapshots balances at certain block numbers.
+
+Considering the above-mentioned behavior, the CLI should calculate the recommended gas limit as follows:
+- `recommendedGas = estimatedGas`, if `estimatedGas > upperGasLimit` or
+- `recommendedGas = estimatedGas * LAST_BLOCK_GAS_LIMIT_FACTOR` with a maximum value of `upperGasLimit`
```
Comment (0xGabi) [inline Specification.md]:
```suggestion
- `recommendedGas = estimatedGas * DEFAULT_GAS_FUZZ_FACTOR` with a maximum value of `upperGasLimit`
```
